apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: combined-secrets
  namespace: qa-backend
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretstore
    kind: SecretStore
  target:
    name: combined-secrets
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: scheme-management-db-credentials-qa
        property: master_password
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: AwsSecrets
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: AwsSecrets
        property: AWS_SECRET_ACCESS_KEY
