apiVersion: v1
kind: Service
metadata:
  name: frontend-{{DEPLOY_NAME}}
  namespace: qa-frontend
spec:
  selector:
    app: frontend-{{DEPLOY_NAME}}
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
